
[font.normal]
family = "SourceCodePro"
style = "Regular"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

[general]
import = [
    "~/.config/alacritty/themes/themes/inferno.toml"
]

